# Version of Docker-compose
version: '3.9'
services:
  # Add the node-js service
  node:
    # Name of the dockerfile
    build: ./server
    container_name: node-container
    ports:
      # Host port:Container port
      - '4000:4000'
    volumes:
      # Bind-mounts configuration
      - ./server:/app
      # Ignoring any changes made in the "node_modules" folder
      - ./app/node_modules
  vue:
    # Name of the dockerfile
    build: ./client
    container_name: vue-container
    ports:
      # Host port:Container port
      - '3000:3000'
    volumes:
      # Bind-mounts configuration
      - ./client:/app
      # Ignoring any changes made in the "node_modules" folder
      - ./app/node_modules
    stdin_open: true
    tty: true
